use_frameworks!

platform :ios, '9.0'

target 'TCLGoogleMobileAds_Example' do
  pod 'TCLGoogleMobileAds', :path => '../'
  
  pod 'Masonry'

  target 'TCLGoogleMobileAds_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
